// Generated by `pnpm palettes` from packages/core/scripts/biome-photos. Do not edit.
import type { Hex, PaletteBiome, RampName } from './palette.ts';

export type BiomePhoto = {
  readonly source: string;
  readonly author: string;
  readonly licence: string;
};

/** A dominant photo colour, the ramp colour it snaps to, and its share of the biome's pixels. */
export type PhotoCluster = { readonly colour: Hex; readonly snapped: Hex; readonly share: number };

/** A proposed ramp and the pixel share it covers that ramps earlier in the list do not. */
export type RampProposal = { readonly ramp: RampName; readonly share: number };

/** What a biome's reference photos look like once snapped to the master palette. */
export type BiomePhotoPalette = {
  readonly photos: readonly BiomePhoto[];
  readonly clusters: readonly PhotoCluster[];
  readonly ramps: readonly RampProposal[];
};

export const BIOME_PHOTO_PALETTES: Record<PaletteBiome, BiomePhotoPalette> = {
  meadow: {
    photos: [
      {
        source: 'https://commons.wikimedia.org/wiki/File:Wildflower_Meadow_(6997737191).jpg',
        author: 'Mount Rainier National Park from Ashford, WA, United States',
        licence: 'Public domain',
      },
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Little_sunflower_in_a_wildflower_meadow_(10678109245).jpg',
        author: 'Intermountain Region US Forest Service',
        licence: 'Public domain',
      },
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Horses_gallop_toward_the_camera_in_a_wildflower-rich_National_Park_Service_meadow_in_Johnson_City,_Texas_LCCN2014633689.tif',
        author: 'Carol M. Highsmith',
        licence: 'Public domain',
      },
    ],
    clusters: [
      { colour: '#878F4D', snapped: '#ADBC3A', share: 0.125 },
      { colour: '#65773C', snapped: '#74A334', share: 0.113 },
      { colour: '#646664', snapped: '#8D977F', share: 0.105 },
      { colour: '#4A5C29', snapped: '#74A334', share: 0.103 },
      { colour: '#807F85', snapped: '#A4B8DA', share: 0.096 },
      { colour: '#313B23', snapped: '#56864C', share: 0.096 },
      { colour: '#4B4C48', snapped: '#8E7C73', share: 0.084 },
      { colour: '#A2A0A5', snapped: '#D2C9C9', share: 0.065 },
      { colour: '#AFA945', snapped: '#ADBC3A', share: 0.062 },
      { colour: '#1A2017', snapped: '#5F7160', share: 0.061 },
      { colour: '#CDD2D3', snapped: '#F2EAF1', share: 0.05 },
      { colour: '#EDE74F', snapped: '#D5D66B', share: 0.039 },
    ],
    ramps: [
      { ramp: 'grass', share: 0.538 },
      { ramp: 'sage', share: 0.166 },
      { ramp: 'granite', share: 0.149 },
      { ramp: 'snow', share: 0.147 },
    ],
  },
  forest: {
    photos: [
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Old_Growth_Ridge_National_Recreation_Trail_(49968731817).jpg',
        author: 'BLM Oregon & Washington',
        licence: 'Public domain',
      },
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Old_Growth_Ridge_National_Recreation_Trail_(49967953768).jpg',
        author: 'BLM Oregon & Washington',
        licence: 'Public domain',
      },
    ],
    clusters: [
      { colour: '#303629', snapped: '#5F7160', share: 0.127 },
      { colour: '#252620', snapped: '#5F7160', share: 0.112 },
      { colour: '#3A4E2E', snapped: '#56864C', share: 0.097 },
      { colour: '#464042', snapped: '#8E7C73', share: 0.092 },
      { colour: '#171711', snapped: '#695953', share: 0.088 },
      { colour: '#5C5855', snapped: '#8D977F', share: 0.085 },
      { colour: '#777B65', snapped: '#B3957F', share: 0.08 },
      { colour: '#0A0906', snapped: '#4E484A', share: 0.078 },
      { colour: '#52693B', snapped: '#7FA24A', share: 0.068 },
      { colour: '#969C7C', snapped: '#D2B37D', share: 0.063 },
      { colour: '#F3F6E5', snapped: '#FFFFFF', share: 0.06 },
      { colour: '#C0C5A8', snapped: '#EECF9B', share: 0.05 },
    ],
    ramps: [
      { ramp: 'stone', share: 0.402 },
      { ramp: 'granite', share: 0.26 },
      { ramp: 'cactus', share: 0.165 },
      { ramp: 'sand', share: 0.113 },
      { ramp: 'snow', share: 0.06 },
    ],
  },
  lakeland: {
    photos: [
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Gfp-minnesota-voyaguers-national-park-crane-lake-shore.jpg',
        author: 'Yinan Chen',
        licence: 'Public domain',
      },
      {
        source:
          'https://commons.wikimedia.org/wiki/File:R31_-_Lost_Bay_East_view_of_rock_boat_access_from_shore_(6f6f13d2-40dd-4780-b016-fdd578a8af9a).JPG',
        author: 'NPS',
        licence: 'Public domain',
      },
    ],
    clusters: [
      { colour: '#ACADAA', snapped: '#D2C9C9', share: 0.156 },
      { colour: '#979593', snapped: '#ABC2BC', share: 0.121 },
      { colour: '#212B26', snapped: '#5F7160', share: 0.114 },
      { colour: '#C3C4BF', snapped: '#D2C9C9', share: 0.108 },
      { colour: '#3D442E', snapped: '#56864C', share: 0.096 },
      { colour: '#5B6145', snapped: '#8D977F', share: 0.09 },
      { colour: '#0B110E', snapped: '#345A52', share: 0.066 },
      { colour: '#71787E', snapped: '#79B8CE', share: 0.065 },
      { colour: '#7C9ECC', snapped: '#A4B8DA', share: 0.054 },
      { colour: '#828C50', snapped: '#ADBC3A', share: 0.049 },
      { colour: '#EBEBE2', snapped: '#F2EAF1', share: 0.044 },
      { colour: '#314B75', snapped: '#7C88B8', share: 0.038 },
    ],
    ramps: [
      { ramp: 'sage', share: 0.39 },
      { ramp: 'granite', share: 0.264 },
      { ramp: 'grass', share: 0.144 },
      { ramp: 'snow', share: 0.136 },
      { ramp: 'water', share: 0.065 },
    ],
  },
  scrubland: {
    photos: [
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Sagebrush_Sea_adjacent_to_Seedskadee_National_Wildlife_Refuge_(26666619704).jpg',
        author: 'USFWS Mountain-Prairie',
        licence: 'Public domain',
      },
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Fossil_Butte_is_capped_by_limestone_deposited_by_ancient_Fossil_Lake,_part_of_the_famous_Green_River_Formation._Sagebrush_steppe_(f1cf9c14-155d-451f-67cf-1094ad7ca5d1).jpg',
        author: 'NPS photo',
        licence: 'Public domain',
      },
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Driving_in_Oregon%27s_sagebrush_sea_(40934507293).jpg',
        author: 'BLM Oregon & Washington',
        licence: 'Public domain',
      },
    ],
    clusters: [
      { colour: '#61594A', snapped: '#8D977F', share: 0.132 },
      { colour: '#514B3A', snapped: '#90775E', share: 0.113 },
      { colour: '#413D2D', snapped: '#90775E', share: 0.102 },
      { colour: '#302D1F', snapped: '#816855', share: 0.093 },
      { colour: '#A79868', snapped: '#D2B37D', share: 0.092 },
      { colour: '#70675C', snapped: '#B3957F', share: 0.09 },
      { colour: '#8E8156', snapped: '#D2B37D', share: 0.088 },
      { colour: '#C1B17F', snapped: '#F1C471', share: 0.082 },
      { colour: '#1E1B0F', snapped: '#695953', share: 0.069 },
      { colour: '#756A3B', snapped: '#A8A129', share: 0.065 },
      { colour: '#DFCF9F', snapped: '#FFE18D', share: 0.044 },
      { colour: '#0C0601', snapped: '#4E484A', share: 0.03 },
    ],
    ramps: [
      { ramp: 'soil', share: 0.498 },
      { ramp: 'straw', share: 0.327 },
      { ramp: 'sage', share: 0.132 },
      { ramp: 'gold', share: 0.044 },
    ],
  },
  desert: {
    photos: [
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Colorado_Great_Sand_Dunes_National_Park.jpg',
        author: 'Mshuang2',
        licence: 'CC0',
      },
      {
        source: 'https://commons.wikimedia.org/wiki/File:Joshua_Tree_Landscape_(54268798660).jpg',
        author: 'Joshua Tree National Park',
        licence: 'Public domain',
      },
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Saguaro_National_Park_Saguaro_Landscape_9876.jpg',
        author: 'National Park Service Digital Image Archives',
        licence: 'Public domain',
      },
    ],
    clusters: [
      { colour: '#CCB9AF', snapped: '#FFCBA9', share: 0.181 },
      { colour: '#B9A69B', snapped: '#D2C9C9', share: 0.124 },
      { colour: '#675641', snapped: '#BD7959', share: 0.113 },
      { colour: '#4F3F2E', snapped: '#90775E', share: 0.101 },
      { colour: '#9B9176', snapped: '#D2B37D', share: 0.082 },
      { colour: '#312719', snapped: '#816855', share: 0.078 },
      { colour: '#A9C5E1', snapped: '#B8DCE5', share: 0.067 },
      { colour: '#7D7356', snapped: '#C8966B', share: 0.065 },
      { colour: '#96B0CC', snapped: '#A4B8DA', share: 0.05 },
      { colour: '#E2E1A8', snapped: '#FFE18D', share: 0.047 },
      { colour: '#BABC73', snapped: '#D5D66B', share: 0.047 },
      { colour: '#140C04', snapped: '#695953', share: 0.045 },
    ],
    ramps: [
      { ramp: 'sand', share: 0.26 },
      { ramp: 'soil', share: 0.224 },
      { ramp: 'rose', share: 0.181 },
      { ramp: 'granite', share: 0.124 },
      { ramp: 'snow', share: 0.117 },
      { ramp: 'gold', share: 0.047 },
      { ramp: 'grass', share: 0.047 },
    ],
  },
  highlands: {
    photos: [
      {
        source: 'https://commons.wikimedia.org/wiki/File:Moorland_on_Beinn_Narnain.webp',
        author: 'Rowyn flowerdew',
        licence: 'CC0',
      },
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Stuc_a_chroin_and_keltie_water,_moorland_trossachs.webp',
        author: 'Rowyn flowerdew',
        licence: 'CC0',
      },
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Besenheide_(wei%C3%9Fer_Busch,_Wangerooge).jpg',
        author: 'Rhetos',
        licence: 'CC0',
      },
    ],
    clusters: [
      { colour: '#826A52', snapped: '#C8966B', share: 0.16 },
      { colour: '#947C5E', snapped: '#C8966B', share: 0.132 },
      { colour: '#705943', snapped: '#BD7959', share: 0.129 },
      { colour: '#A68F7D', snapped: '#D2B37D', share: 0.125 },
      { colour: '#564A3D', snapped: '#8E7C73', share: 0.106 },
      { colour: '#BBA599', snapped: '#D2C9C9', share: 0.084 },
      { colour: '#3C3933', snapped: '#8E7C73', share: 0.07 },
      { colour: '#837B83', snapped: '#D3A2C0', share: 0.065 },
      { colour: '#556575', snapped: '#7C88B8', share: 0.046 },
      { colour: '#21201E', snapped: '#695953', share: 0.034 },
      { colour: '#DAD7C7', snapped: '#FCE2CA', share: 0.028 },
      { colour: '#75A3BF', snapped: '#71DDEE', share: 0.021 },
    ],
    ramps: [
      { ramp: 'sand', share: 0.546 },
      { ramp: 'granite', share: 0.294 },
      { ramp: 'heather', share: 0.065 },
      { ramp: 'snow', share: 0.046 },
      { ramp: 'dune', share: 0.028 },
      { ramp: 'water', share: 0.021 },
    ],
  },
  taiga: {
    photos: [
      {
        source: 'https://commons.wikimedia.org/wiki/File:Snowy_boreal_forest_(51267438559).jpg',
        author: 'BLM Alaska',
        licence: 'Public domain',
      },
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Spruce_trees_in_the_snow_(52828594353).jpg',
        author: 'USFWSAlaska',
        licence: 'Public domain',
      },
    ],
    clusters: [
      { colour: '#ECEFF6', snapped: '#F2EAF1', share: 0.293 },
      { colour: '#DADADA', snapped: '#F2EAF1', share: 0.127 },
      { colour: '#D0D0D1', snapped: '#F2EAF1', share: 0.095 },
      { colour: '#C3C4C5', snapped: '#B8DCE5', share: 0.091 },
      { colour: '#F1F3F9', snapped: '#FFFFFF', share: 0.085 },
      { colour: '#6F7174', snapped: '#B3957F', share: 0.073 },
      { colour: '#ADAFB3', snapped: '#D2C9C9', share: 0.064 },
      { colour: '#919295', snapped: '#ABC2BC', share: 0.063 },
      { colour: '#4D4F52', snapped: '#8E7C73', share: 0.05 },
      { colour: '#E3E4E7', snapped: '#F2EAF1', share: 0.03 },
      { colour: '#FAFCFE', snapped: '#FFFFFF', share: 0.015 },
      { colour: '#161616', snapped: '#695953', share: 0.014 },
    ],
    ramps: [
      { ramp: 'snow', share: 0.736 },
      { ramp: 'granite', share: 0.201 },
      { ramp: 'sage', share: 0.063 },
    ],
  },
  tundra: {
    photos: [
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Arctic_national_wildlife_refuge_tundra.jpg',
        author: 'U.S. Fish and Wildlife Service',
        licence: 'Public domain',
      },
      {
        source:
          'https://commons.wikimedia.org/wiki/File:Tundra_plants_take_refuge_among_rocks_to_find_protection_from_harsh,_dessicating_winds_in_the_high_elevations_of_the_Arctic._(c4f1b0ba-1dd8-b71c-07c1-7b0dc013e5b9).jpg',
        author: 'NPS Photo',
        licence: 'Public domain',
      },
    ],
    clusters: [
      { colour: '#4E412E', snapped: '#90775E', share: 0.104 },
      { colour: '#34291C', snapped: '#816855', share: 0.097 },
      { colour: '#B49E56', snapped: '#F1C471', share: 0.096 },
      { colour: '#070302', snapped: '#4E484A', share: 0.095 },
      { colour: '#907A3B', snapped: '#A8A129', share: 0.091 },
      { colour: '#1C120B', snapped: '#695953', share: 0.091 },
      { colour: '#D2C899', snapped: '#FFE18D', share: 0.079 },
      { colour: '#6F5A26', snapped: '#A8A129', share: 0.075 },
      { colour: '#EAEADE', snapped: '#F2EAF1', share: 0.072 },
      { colour: '#918580', snapped: '#D3A2C0', share: 0.068 },
      { colour: '#6C605F', snapped: '#B3957F', share: 0.067 },
      { colour: '#B1ABA8', snapped: '#D2C9C9', share: 0.067 },
    ],
    ramps: [
      { ramp: 'soil', share: 0.453 },
      { ramp: 'straw', share: 0.262 },
      { ramp: 'gold', share: 0.079 },
      { ramp: 'snow', share: 0.072 },
      { ramp: 'heather', share: 0.068 },
      { ramp: 'granite', share: 0.067 },
    ],
  },
};
