import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { format, resolveConfig } from 'prettier';
import { BIOME_RAMPS, PALETTE_BIOMES, type PaletteBiome } from '../src/palette.ts';
import type { BiomePhotoPalette } from '../src/biome-photo-palettes.ts';
import { biomePalette, parseSources, type PhotoSource } from './photo-palette.ts';

const PHOTOS = resolve(import.meta.dirname, 'biome-photos');
const OUT = resolve(import.meta.dirname, '../src/biome-photo-palettes.ts');

/** The committed thumbnail, fetched from Wikimedia Commons first if it is not on disk yet. */
async function photoBytes({ file, thumbnail }: PhotoSource): Promise<Buffer> {
  const path = resolve(PHOTOS, file);
  if (!existsSync(path)) {
    const response = await fetch(thumbnail, {
      headers: { 'User-Agent': 'geekity-explore-palettes/1.0 (github.com/geekitycom/explore)' },
    });
    if (!response.ok) throw new Error(`${file}: ${response.status} fetching ${thumbnail}`);
    writeFileSync(path, Buffer.from(await response.arrayBuffer()));
    console.log(`fetched ${file}`);
  }
  return readFileSync(path);
}

const HEADER = `// Generated by \`pnpm palettes\` from packages/core/scripts/biome-photos. Do not edit.
import type { Hex, PaletteBiome, RampName } from './palette.ts';

export type BiomePhoto = {
  readonly source: string;
  readonly author: string;
  readonly licence: string;
};

/** A dominant photo colour, the ramp colour it snaps to, and its share of the biome's pixels. */
export type PhotoCluster = { readonly colour: Hex; readonly snapped: Hex; readonly share: number };

/** A proposed ramp and the pixel share it covers that ramps earlier in the list do not. */
export type RampProposal = { readonly ramp: RampName; readonly share: number };

/** What a biome's reference photos look like once snapped to the master palette. */
export type BiomePhotoPalette = {
  readonly photos: readonly BiomePhoto[];
  readonly clusters: readonly PhotoCluster[];
  readonly ramps: readonly RampProposal[];
};

`;

const sources = parseSources(JSON.parse(readFileSync(resolve(PHOTOS, 'sources.json'), 'utf8')));
const palettes = {} as Record<PaletteBiome, BiomePhotoPalette>;
for (const biome of PALETTE_BIOMES) {
  const photos = sources.filter((s) => s.biome === biome);
  if (photos.length === 0) throw new Error(`no photos for ${biome}`);
  const palette = biomePalette(photos, await Promise.all(photos.map(photoBytes)));
  palettes[biome] = palette;

  const chosen = new Set([...BIOME_RAMPS[biome].ground, ...BIOME_RAMPS[biome].flora]);
  const proposed = palette.ramps.map(({ ramp, share }) => `${ramp} ${Math.round(share * 100)}%`);
  const unchosen = palette.ramps.map(({ ramp }) => ramp).filter((ramp) => !chosen.has(ramp));
  console.log(`${biome.padEnd(10)} ${proposed.join(', ')}`);
  if (unchosen.length > 0)
    console.log(`${''.padEnd(10)} not in BIOME_RAMPS: ${unchosen.join(', ')}`);
}

const source = `${HEADER}export const BIOME_PHOTO_PALETTES: Record<PaletteBiome, BiomePhotoPalette> = ${JSON.stringify(palettes)};\n`;
writeFileSync(OUT, await format(source, { ...(await resolveConfig(OUT)), filepath: OUT }));
console.log(`wrote ${OUT}`);
